### ISSUE TITLE
Missing v1 tag

### ISSUE THREAD

**Issue by Methuselah96** [leonardochaia/dotnet-affected-action#156]
The examples in the README reference this action using `leonardochaia/dotnet-affected@v1`, however this doesn't work since there is no `v1` tag. [Adding a `v1` tag](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management) should resolve this.

**Comment by leonardochaia** [comment]
hi @Methuselah96 , tag `v1` [has been created](https://github.com/leonardochaia/dotnet-affected-action/releases/tag/v1)

I hope I remember to keep the tag up to date :smile:
